### ISSUE TITLE
sorry，刚刚接触这个dubbo服务问一下，第二步打包怎么打包？

### ISSUE THREAD

**Issue by yuchong2018** [nyvi/dubbo#1]
1、刚刚接触这个dubbo服务问一下，第二步打包怎么打包？你的demo代码中怎么启动生成和消费者

> 启动dubbo-admin客户端(需自己打包运行)
> 启动生产者(dubbo-provider)
> 启动消费者(duboo-consumer)

**Comment by nyvi** [comment]
打包的话:
1. git clone https://github.com/apache/incubator-dubbo-ops
2. cd incubator-dubbo-ops && mvn package
3. 到dubbo-admin下找到对应的war包放到tomcat

启动的话
生产者找到DubboProviderLauncher.java 右击直接运行
消费者找到DubboConsumerLauncher.java 右击直接运行
